# Site settings

url: "https://hopetech.github.io"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Elie Tournier"
title: "{ Elie Tournier }"
description: "Blog and website of Elie Tournier, blogging mainly for tech. Opinions expressed are mine."
keywords: "elie, tournier, personal, Mesa, XOrg"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
pocket-share: True

disqus-shortname: "elie"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "August 15 - 23, 2016"
    description: "Final evaluations"  
  - image: "/img/timeline/baracktocat.jpg"
    date: "June 27, 2016 - August 15, 2016"
    description: "Keep coding"
  - image: "/img/timeline/spidertocat.png"
    date: "June 20 - 27, 2016"
    description: "Midterm evaluations"
  - image: "/img/timeline/baracktocat.jpg"
    date: "May 23, 2016 - June 27, 2016"
    description: "Started coding"
  - image: "/img/timeline/xorg.jpg"
    date: "April 22, 2016 - May 22, 2016"
    description: "Community Bonding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "tournier.elie@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "My name is Elie Tournier. I'm a medical ICT student at Telecom Physique Strasbourg, France. Open-source entousiast, I contribute to Mesa by implementing a double precision floating point library."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/elietournier"
  - title: "github"
    url: "https://github.com/hopetech"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
